### ISSUE TITLE
Composer issue?

### ISSUE THREAD

**Issue by JPustkuchen** [acquia/drupal-spec-tool#1] opened 2018-06-07 11:45 UTC
Using version ^1.1 for acquia/drupal-spec-tool
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - acquia/drupal-spec-tool v1.1 requires traviscarden/behat-table-comparison ^0.2.1 -> satisfiable by traviscarden/behat-table-comparison[v0.2.1].
    - Installation request for acquia/drupal-spec-tool ^1.1 -> satisfiable by acquia/drupal-spec-tool[v1.1].
    - Conclusion: remove sebastian/diff 2.0.1
    - Conclusion: don't install sebastian/diff 2.0.1
    - traviscarden/behat-table-comparison v0.2.1 requires sebastian/diff ^1.4 -> satisfiable by sebastian/diff[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.x-dev].
    - Can only install one of: sebastian/diff[1.4.0, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.1, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.2, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.3, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.x-dev, 2.0.1].
    - Installation request for sebastian/diff (locked at 2.0.1) -> satisfiable by sebastian/diff[2.0.1].

Installation failed, reverting ./composer.json to its original content.

Then tried:
composer remove sebastian/diff
sebastian/diff is not required in your composer.json and has not been removed

Is this fixable in the projects composer file?

**Comment by fbray** [comment] 2018-06-08 21:21
I had this same issue today when trying to use the Spec Tool with Acquia Lightening distro.

Steps to reproduce:
1. `composer create-project acquia/lightning-project lightning_project`
1. `composer require acquia/drupal-spec-tool`

Output:
```
$ composer require acquia/drupal-spec-tool
Using version ^1.1 for acquia/drupal-spec-tool
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - acquia/drupal-spec-tool v1.1 requires traviscarden/behat-table-comparison ^0.2.1 -> satisfiable by traviscarden/behat-table-comparison[v0.2.1].
    - Installation request for acquia/drupal-spec-tool ^1.1 -> satisfiable by acquia/drupal-spec-tool[v1.1].
    - Conclusion: remove sebastian/diff 2.0.1
    - Conclusion: don't install sebastian/diff 2.0.1
    - traviscarden/behat-table-comparison v0.2.1 requires sebastian/diff ^1.4 -> satisfiable by sebastian/diff[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.x-dev].
    - Can only install one of: sebastian/diff[1.4.0, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.1, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.2, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.3, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.x-dev, 2.0.1].
    - Installation request for sebastian/diff (locked at 2.0.1) -> satisfiable by sebastian/diff[2.0.1].


Installation failed, reverting ./composer.json to its original content.
```

After running a `composer depends sebastian/diff` within the Lightening distribution project, the following is returned:

```
$ composer depends sebastian/diff
phpunit/phpunit       6.5.8  requires  sebastian/diff (^2.0)
sebastian/comparator  2.1.3  requires  sebastian/diff (^2.0 || ^3.0)
```
Running the same command within the Drupal Spec Tool project:

```
$ composer depends sebastian/diff
traviscarden/behat-table-comparison  v0.2.1  requires  sebastian/diff (^1.4)
```


So either the behat table comparison tool should update its dependencies to a higher version of sebastian diff, or another tool should be used in order to support both Acquia Lightening and this tool simultaneously.

**Comment by TravisCarden** [comment] 2018-07-02 17:31
Thanks for the report! I'll look into this.

**Comment by TravisCarden** [comment] 2018-07-03 18:10
Okay, I believe the problem is fixed now. I was able to follow the steps in https://github.com/acquia/drupal-spec-tool/issues/1#issuecomment-395893807 without producing the error. I'm closing the issue. Please re-open if the problem persists for you. (By the way, I'm sorry it took me so long to respond here. I didn't realize I wasn't watching the repo and so wasn't getting email notifications.)

**Closed by TravisCarden** 2018-07-03 18:10 UTC
